### ISSUE TITLE
Don't show people how to store secrets in plaintext files

### ISSUE THREAD

**Issue by readysetawesome** [cupnoodle/rails-ansible#4]
The approach starts with copying secrets that will never even be used: 
https://github.com/cupnoodle/rails-ansible/blob/master/vars/envs.yml#L10
`  SECRET_KEY_BASE: .... `
https://github.com/cupnoodle/rails-ansible/blob/master/vars/vars.yml#L9
` deploy_user_password `

The guide proceeds to encourage people to encode both the Rails Master Secret and database passwords in plaintext in playbook files. All very bad practice from a DevOps perspective.  

Why? This enables bad habits and misleads beginners. System deployments should be designed from the ground-up with these secrets managed as part of the process, by a secret manager whose secrets can be injected into environments by service managers.

**Comment by cupnoodle** [comment]
Thanks for the suggestion, yeah storing secrets in plaintext in playbook files isn't a good practice in an organization, I did this ansible repository aimed for non dev-ops personnel who intend to use it personally.

Would you mind submitting a PR to improve this?

**Comment by cupnoodle** [comment]
Nevermind I added some introductory ansible-vault command on the README.md file just now, hope this is well
